pipeline {
    agent any
    parameters {
        choice(name: 'TEST_ENV', choices: ['dev', 'staging', 'prod'], description: 'Environment for tests')
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Git branch')
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: "${BRANCH_NAME}", url: 'https://your-repo-url.git'
            }
        }
        stage('Run API Tests') {
            steps {
                script {
                    sh 'mvn test -Denv=${TEST_ENV}'
                }
            }
        }
        stage('Generate Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
            }
        }
    }
}